"""create financial analyses table

Revision ID: 28664f0e8825
Revises: f83b6405fdd6
Create Date: 2026-09-09 21:57:45.759294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28664f0e8825'
down_revision: Union[str, Sequence[str], None] = 'f83b6405fdd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('initial_investment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fixed_costs', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('variable_costs', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('roi', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('profit_margin', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('break_even', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_analyses_contract_id'), 'financial_analyses', ['contract_id'], unique=True)
    op.create_index(op.f('ix_financial_analyses_id'), 'financial_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_analyses_id'), table_name='financial_analyses')
    op.drop_index(op.f('ix_financial_analyses_contract_id'), table_name='financial_analyses')
    op.drop_table('financial_analyses')
    # ### end Alembic commands ###
