"""add decision scores

Revision ID: 33f379dd1fcb
Revises: a328fdd9ad53
Create Date: 2026-09-09 23:44:35.577382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f379dd1fcb'
down_revision: Union[str, Sequence[str], None] = 'a328fdd9ad53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('financial_score', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('contract_value_score', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('financial_weight', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('risk_weight', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('contract_value_weight', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_scores_contract_id'), 'decision_scores', ['contract_id'], unique=True)
    op.create_index(op.f('ix_decision_scores_id'), 'decision_scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_scores_id'), table_name='decision_scores')
    op.drop_index(op.f('ix_decision_scores_contract_id'), table_name='decision_scores')
    op.drop_table('decision_scores')
    # ### end Alembic commands ###
