"""Add contract storage key

Revision ID: 4ec31edc97e0
Revises: 70af43c0fbab
Create Date: 2026-09-07 15:36:58.193396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec31edc97e0'
down_revision: Union[str, Sequence[str], None] = '70af43c0fbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('storage_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'storage_key')
    # ### end Alembic commands ###
