"""Add contract intake metadata

Revision ID: 70af43c0fbab
Revises: 34e21bd426f9
Create Date: 2026-09-07 13:54:41.810090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70af43c0fbab'
down_revision: Union[str, Sequence[str], None] = '34e21bd426f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "contracts",
    sa.Column(
        "source_type",
        sa.String(length=50),
        nullable=False,
        server_default="manual",
    ),
)
    op.add_column('contracts', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('contracts', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column(
    "contracts",
    sa.Column(
        "status",
        sa.String(length=50),
        nullable=False,
        server_default="pending",
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'status')
    op.drop_column('contracts', 'mime_type')
    op.drop_column('contracts', 'original_filename')
    op.drop_column('contracts', 'source_type')
    # ### end Alembic commands ###
