"""add contract information dates and risk terms

Revision ID: 8442245796a3
Revises: dd2a325e77d4
Create Date: 2026-09-21 18:16:13.776755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8442245796a3'
down_revision: Union[str, Sequence[str], None] = 'dd2a325e77d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_information', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('contract_information', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('contract_information', sa.Column('penalties', sa.Text(), nullable=True))
    op.add_column('contract_information', sa.Column('liabilities', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_information', 'liabilities')
    op.drop_column('contract_information', 'penalties')
    op.drop_column('contract_information', 'end_date')
    op.drop_column('contract_information', 'start_date')
    # ### end Alembic commands ###
