"""add contract information

Revision ID: 889474d59f7b
Revises: 33f379dd1fcb
Create Date: 2026-09-16 15:54:40.314453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889474d59f7b'
down_revision: Union[str, Sequence[str], None] = '33f379dd1fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('renewal_terms', sa.Text(), nullable=True),
    sa.Column('termination_terms', sa.Text(), nullable=True),
    sa.Column('obligations', sa.Text(), nullable=True),
    sa.Column('dependencies', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_information_contract_id'), 'contract_information', ['contract_id'], unique=True)
    op.create_index(op.f('ix_contract_information_id'), 'contract_information', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_information_id'), table_name='contract_information')
    op.drop_index(op.f('ix_contract_information_contract_id'), table_name='contract_information')
    op.drop_table('contract_information')
    # ### end Alembic commands ###
