"""add contract decisions

Revision ID: dae395f3b20f
Revises: 8442245796a3
Create Date: 2026-09-22 14:49:03.324237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae395f3b20f'
down_revision: Union[str, Sequence[str], None] = '8442245796a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_decisions_contract_id'), 'contract_decisions', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_decisions_decided_at'), 'contract_decisions', ['decided_at'], unique=False)
    op.create_index(op.f('ix_contract_decisions_decided_by'), 'contract_decisions', ['decided_by'], unique=False)
    op.create_index(op.f('ix_contract_decisions_decision'), 'contract_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_contract_decisions_id'), 'contract_decisions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_decisions_id'), table_name='contract_decisions')
    op.drop_index(op.f('ix_contract_decisions_decision'), table_name='contract_decisions')
    op.drop_index(op.f('ix_contract_decisions_decided_by'), table_name='contract_decisions')
    op.drop_index(op.f('ix_contract_decisions_decided_at'), table_name='contract_decisions')
    op.drop_index(op.f('ix_contract_decisions_contract_id'), table_name='contract_decisions')
    op.drop_table('contract_decisions')
    # ### end Alembic commands ###
