"""Create contract documents table

Revision ID: f83b6405fdd6
Revises: 4ec31edc97e0
Create Date: 2026-09-07 16:44:38.374961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83b6405fdd6'
down_revision: Union[str, Sequence[str], None] = '4ec31edc97e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_documents_contract_id'), 'contract_documents', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_documents_id'), 'contract_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_documents_id'), table_name='contract_documents')
    op.drop_index(op.f('ix_contract_documents_contract_id'), table_name='contract_documents')
    op.drop_table('contract_documents')
    # ### end Alembic commands ###
